plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.xaan'
version = '0.0.1'

java {
    sourceCompatibility = '17'
    targetCompatibility = '17'
}

repositories {
    mavenCentral()
}

dependencies {
    // Spring Vault core
    api 'org.springframework.vault:spring-vault-core:3.1.0'
    
    // Spring context for @Service
    api 'org.springframework:spring-context:6.2.0'
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            name = 'local'
            url = layout.buildDirectory.dir('repos/local')
        }
    }
}

test {
    useJUnitPlatform()
}